spring:
  datasource:
    url: jdbc:h2:mem:persondb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 15
        limitRefreshPeriod: 1s
        timeoutDuration: 100ms